# Generated by Django 5.2.4 on 2025-10-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.AddField(
            model_name='project',
            name='jobtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
