# Generated by Django 5.2.4 on 2025-10-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_slug_project_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='jobtitle',
            field=models.CharField(blank=True, default=True, max_length=75),
        ),
    ]
