# Generated by Django 5.2.4 on 2025-10-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_jobtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date',
            new_name='startdate',
        ),
        migrations.AddField(
            model_name='project',
            name='enddate',
            field=models.DateField(blank=True),
        ),
    ]
