# Generated by Django 5.2.4 on 2025-10-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectname',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
